---
title: "Ejercicio 2"
author: "Equipo"
date: "2024-03-26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 2. Modelos lineales generalizados para datos continuos

Considere los mismos datos que en la pregunta 1, la base de datos Preg1B.csv con información sobre 295 pacientes seleccionados de forma aleatoria. Se desea analizar si existe una asociación entre la presión arterial sistólica (bpsystol) y el índice de masa corporal (bmi), considerando el sexo (sex: 1-hombre, 2-mujer) y la edad (age) de los pacientes.



i. Explorando los diferentes modelos lineales generalizados comúnmente usados cuando la variable dependiente es continua (normal, gamma, inversa gaussiana), presente un modelo que le parezca adecuado para modelar E(bpsystol; bmi, sex, age). Considere por simplicidad que no hay interacción entre las covariables del modelo. Deberá indicar con claridad cuál es la expresión matemática que se usa para modelar E(bpsystol; bmi, sex, age), así como describir el procedimiento y criterio usado para seleccionar el modelo.


ii. Repita los incisos iii) y iv) de la pregunta 1 con el modelo en i).



iii. Comparando el modelo en i) con el usado en la pregunta 1, compare las conclusiones e interpretaciones que se pueden obtener e indique qué modelo prefiere usar. Argumente con claridad su respuesta, por ejemplo, debe incluir los valores de AIC o BIC, así como ventajas y desventajas en la interpretación.


### i) Explorando modelos con variable dependiente contínua. 

### ii) Asociación entre masa corporal y presión arterial sistólica, y estimación puntual. 

### iii) Comparativo modelo de regresión lineal múltiple contra modelo lineal generalizado. 



